### ISSUE TITLE
Skaled won't be restarted again after rotation in case of a temporary error

### ISSUE THREAD

**Issue by badrogger** [skalenetwork/skale-admin#1004]
**Describe the bug**
Admin exit monitor worker with error and restart again as a last level rescue mechanism. But in case if some fault occured during the last rotation stage (updating config and restarting schain containers) before skaled container is restarted it still will be in the exit state after the next worker iteration.  

**To Reproduce**
1. Rotate chain.
2. Wait until setExitTime request was sent.
3. Stop docker-lvmpy (`systemctl stop docker-lvmpy`)  - to simulate the error.

**Expected behavior**
Skaled would be eventually restarted with a new config. 

**Actual behavior**
Skaled is not restarted until `docker restart` or something equivalent called manually.

**Comment by DmytroNazarenko** [comment]
2.5.3

**Comment by yatsunastya** [comment]
It's necessary to retest it in 2.3 release

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
admin: `2.6.0-beta.0`

**Steps that were used for testing:**
1. Start node rotation and wait till `rotation.json` file is created
2. Stop skale-admin
3. Wait till skaled exits
4. Use `iptables -A INPUT -s 127.0.0.1/24 -p tcp -m tcp --dport 10017 -j ACCEPT`
5. Restart skale-admin and wait for 2 min
6.  Use `iptables -D INPUT -s 127.0.0.1/24 -p tcp -m tcp --dport 10017 -j ACCEPT`

**Result:**
Skaled and IMA are recreated and successfully started working.
