### ISSUE TITLE
Decrease time frame for agent frame

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-admin#1029]
Currently we have 30 mins for IMA agent time frame:
https://github.com/skalenetwork/skale-admin/blob/0a1faef5925d0ea67eeaf676b49ee745b3907830/tools/configs/ima.py#L91

We need to decrease it to 15 minutes, as it was planned since the beginning

**Comment by DmytroNazarenko** [comment]
skale-admin: v2.7.0-beta.0
timestamp:`skale-node/ima_migration_schedule.yaml`

**Comment by EvgeniyZZ** [comment]
Verified: 2.1.0
Introduced ima_migration_schedule.yaml 
After enabling the timestamps, all IMA agent's on skale core nodes are restarted. Active frame started from 0 index.
