### ISSUE TITLE
Skale admin doesn't restart schain monitoring if monitoring hangs 

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skale-admin#1044]
**Describe the bug**
In Skale Admin, there are two processes for each chain - one monitor is responsible for the status of contracts (creating chains, rotating ERC), and the second monitor checks the status of each Skaled container. Sometimes, the chain monitoring process hangs, ceases to initiate checks, and, in case of issues within the Skaled container, fails to perform the specified actions for recovery or restarting of such a Skaled.

**Preconditions:**
16 nodes 
8 active chains 
2 GETH nodes for 8 nodes each
Disabled auto_repair option in container config stream

**Versions:**
skalenetwork/admin:2.5.4-develop.1  

**To Reproduce**
Clear steps for reproduction are missing. 
To investigate, it is necessary for a failure to occur and to increase the log size for Skale-admin on QANet

**Expected behavior**
Skale admin should run 2 monitors after Geth nodes are synced

**Actual state:**
In some cases, skale admin initiates only contract monitoring, but does not restart the schain monitoring if it hangs. 

**Temporary workaround:**
Restart the Skale admin container manually

**Comment by PolinaKiporenko** [comment]
investigate during 2.3 release

**Comment by PolinaKiporenko** [comment]
Temporary workaround - repair with restart admin container

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
Version: 2.8.0-beta.1

As it's not clear how to verify this ticket, it was decided to check that main basic functionality isn't broken.
