### ISSUE TITLE
add `n` to sync node config

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skale-admin#1050]
add `n` - number of the nodes in schain to the `wallets` / `ima` config section. this field is needed by oracle-verifier contract to read number of the nodes in schain

**Comment by PolinaKiporenko** [comment]
related to https://github.com/skalenetwork/skaled/issues/1836

**Comment by OleksanderSalamatov** [comment]
admin:`2.11.0-sync-node.5`

`n` is now present in archive node schain config and is correct value

```
            "wallets": {
                "ima": {
                    "n": 16
                }
            },
```          

Can be closed
