### ISSUE TITLE
Precalculate genesis blocks for v2.1 and previous chains on QA-net

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skale-admin#1052]
The same as https://github.com/skalenetwork/skale-admin/issues/944

Need to precalculate 0 blocks for chains on QA-net. 
```
GEN 1
admin: 2.3.10
hungry-formal-ascella               
big-majestic-oval-SKALE             
international-villainous-zaurak     
ill-informed-friendly-haedi         
rural-colossal-cebalrai             
worrisome-fortunate-talitha         

GEN 2
admin:2.4.0
breakable-anguished-tania-borealis  
skale-innocent-nasty                
```

**Comment by PolinaKiporenko** [comment]
to unblock QA testing as temporary solution will prepare custom chain config

**Comment by DmytroNazarenko** [comment]
[schain-skale-innocent-nasty.json](https://github.com/skalenetwork/skale-admin/files/14495406/schain-skale-innocent-nasty.json)
