### ISSUE TITLE
response for `complaint_bad_data` fails

### ISSUE THREAD

**Issue by olehnikolaiev** [skalenetwork/skale-admin#1054]
`response` function fails during dkg due to the missing variable in `enum`

```
class DKGStep(int, Enum):
    """ Index of DKG step """
    NONE = 0
    BROADCAST = 1
    BROADCAST_VERIFICATION = 2
    ALRIGHT = 3
    ALRIGHT_RECEIVING = 4
    COMPLAINT_NO_BROADCAST = 5
    COMPLAINT_BAD_DATA = 6
    COMPLAINT_NO_ALRIGHT = 7
    COMPLAINT_NO_RESPONSE = 8
    RESPONSE = 9
    KEY_GENERATION = 10
 ```
 
 also, `response` function will not be sent to the smart contract if `skale-admin` fails somewhere between `pre_response` and `response` functions
 
 
 need to fix both issues to ensure that `resposne` mechanism works correctly in case of any complaints during dkg

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
admin: 2.6.1

In case of fake broadcast, after `CompaintBadData` transaction, `Pre Response` and `Response` are sent. 

<img width="1360" alt="Знімок екрана 2024-03-10 о 21 47 49" src="https://github.com/skalenetwork/skale-admin/assets/105824131/599b16dc-69f7-4406-8909-7518c60ce460">


`[2024-03-07 17:41:51,523 INFO][13][rapping-cebalrai][T_0] - core.schains.dkg.utils:258 - sChain: rapping-cebalrai: Complaint received. Sending response ...`
