### ISSUE TITLE
State root mismatch on archival node after start from 0 block from precalculated config

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skale-admin#1097]
**Note**
This bug affects only **new** archival\indexer nodes  

**Describe the bug**
Before the 2.2 Release, the Skale admin generated the genesis block with the actual versions of pre-deployed contracts for each release. To avoid starting from the genesis block, we prepared configurations for each chain with the contract versions used when the schain was created.

**Versions:**
skalenetwork/admin:2.7.0
CONTAINER_CONFIGS_STREAM="legacy-2.4-stable" 

https://github.com/skalenetwork/skale-node/commit/c683ac848722121dc81a979b9e93567d1c1e05ce
**Preconditions**
Skale chain that was created on version 2.1 and subsequently updated through sequential releases up to the V3 version.
Archival node with whitelisted IP 

**To Reproduce**
1. Run init archival node
``skale sync-node init init-env --archive --catchup --historic-state``
2. Check еру state root after 1st snapshot interval 
3. Check eth_getCode for MARIONETTE_IMPLEMENTATION and CONFIG_CONTROLLER_IMPLEMENTATION
```
CONFIG_CONTROLLER_IMPLEMENTATION = 0xD2003000000000000000000000000000000000D2
MARIONETTE_IMPLEMENTATION = 0xd2c0defaCeD20000000000000000000000000000
```

**Expected behavior**
Skaled should have the same state root. 
Pre-deployed contract should be the same on core and archival nodes

**Comment by EvgeniyZZ** [comment]
@oleksandrSydorenkoJ recheck predeployed versions 
Compare skale admin version during schain creation vs skale admin on archive node(requirements.txt file), assume they can be different, in this case we need to rebuild 2.7 version of skale admin
