### ISSUE TITLE
Misleading wallet info

### ISSUE THREAD

**Issue by ebruengwall-ant** [skalenetwork/skale-admin#301]
https://github.com/skalenetwork/skale-admin/blob/49ccb7b70cd6df73201484561a74f0ccfa4bd214/core/schains/utils.py#L31

It's not notifying that wallet has not enough ETH. Info should be framed as: `checking the balance of the node wallet to have enough SKL tokens or ETH`  

Secondly, This is the node wallet. And why there should be at least 0.1 SKALE tokens in the node wallet?

**Comment by dmytrotkk** [comment]
@ebruoguzberk 
Thanks for your feedback!

You're right, that's the node wallet and now we don't have any requirements for the SKL balance for it.
We're working on the fix and notify you as soon as this issue will be resolved.
