### ISSUE TITLE
skale-api doesn't respond on any watchdog requests if there is no connection to SGX

### ISSUE THREAD

**Issue by alexgex** [skalenetwork/skale-admin#804]
**To Reproduce**
Stop SGX server

**Expected behavior**
skale-api should respond on watchdog requests

**Actual result**
skale-api doesn't respond on any watchdog requests

**Comment by badrogger** [comment]
[2.3.4-beta.2](https://github.com/skalenetwork/skale-admin/releases/tag/2.3.4-beta.2)

**Comment by oleksandrSydorenkoJ** [comment]
Checked on Skale Legacy network
still actual for admin:2.3.5

1. stop sgx server 
2. run following commands 
curl http://localhost:3009/status/ima
curl http://localhost:3009/status/btrfs
curl http://localhost:3009/status/public-ip
curl http://localhost:3009/status/check-report
curl http://localhost:3009/status/core 

[api_checks_NOT_connected_sgx.log](https://github.com/skalenetwork/skale-admin/files/8853263/api_checks_NOT_connected_sgx.log)

**Comment by badrogger** [comment]
[2.3.6](https://github.com/skalenetwork/skale-admin/releases/tag/2.3.6)

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Skale Legacy network
versions:
admin:2.3.8-beta.1
watchdog:2.1.0-beta.4

[stoped_sgx_watchdog_checks.log](https://github.com/skalenetwork/skale-admin/files/9095619/stoped_sgx_watchdog_checks.log)
