### ISSUE TITLE
Add ABI check to skale-api for watchdog requests

### ISSUE THREAD

**Issue by alexgex** [skalenetwork/skale-admin#805]
Add a request to skale-api that returns the hash of used ABI.
This request will be used by watchdog to check if correct ABI is used by node components.

**Comment by badrogger** [comment]
skale-admin: 2.3.6
skale-watchdog: 2.1.0-beta.2

**Comment by oleksandrSydorenkoJ** [comment]
Verified on Skale Legacy network
versions:
admin:2.3.8-beta.1
watchdog:2.1.0-beta.4

Steps to reproduce:
1. Stop the SGX server for the current node.
2. Wait 5 minutes and send ``curl http://127.0.0.1:3009/status/sm-abi``
3. Check the result


```
root@ip-172-31-51-8:~# curl http://127.0.0.1:3009/status/sm-abi
{"data": "5ef329a80256c72d8a53f6e8e2f89451b0164e1c8241ac528a57bcfd3708e9ca", "error": null}
```
