### ISSUE TITLE
Add a procedure to update sChain configs when IP is changed on one of the nodes

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/skale-admin#832]
### Reasoning

Although we have a function to change IP on skale-manager smart contracts, these changes are not synchronized with the nodes on the validator's machines. SM part of the code can be found here: https://github.com/skalenetwork/skale-manager/blob/680a04a360696a721a579fb473b5cbc562e720f3/contracts/Nodes.sol#L437

Generally, we recommend elastic IP for all nodes in the network to simplify migration, but some validators still had their IPs attached to the servers. Another case is migration to completely different servers or cloud provider when it's impossible to keep the old IP address. 

That's why we need a procedure to recreate sChain configs on all nodes when one of the nodes in this chain changes its public IP address.

### Limitations

For this feature, we need to ensure that each node in the chain recreates its config and restarts the skaled container in a dedicated timeframe to avoid situations when multiple nodes are down.

### Implementation

To handle dynamic config changes we need:

1. Detect that IP was changed for a node in the chain - this functionality already exists for a firewall rules checker - we should reuse this data to avoid additional calls to skale-manager 
2. Once IP change is detected each node should recreate the sChain config and restart respecting skaled container in a defined time slot.

The proposal here is to use an approach similar to IMA time frames where each node `config_update_ts` will be calculated in the following way:

```
config_update_ts = current_ts + DELAY_CONST * node_index_in_the_chain
```

Let's say that `DELAY_CONST` is 300 seconds, then the node with the `0` index in this chain will update its config immediately, `1st` node will do it after 300 seconds, `2nd` - after 600, etc.

#### Required changes

This proposal requires multiple changes to sChain monitor and database:

1. `config_update_ts` field should be added to the database (null by default)
2. monitor should lookup for an IP change and set `config_update_ts` in the DB
3. if `config_update_ts` is set and when `current_ts >= config_update_ts` - `ConfigUpdateMonitor` should be executed
4. `ConfigUpdateMonitor` should set `config_update_ts` to null in the end of its work. 

```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/skale-manager/issues/1013
```

**Comment by PolinaKiporenko** [comment]
see PRD https://www.notion.so/skalelabs/PRD-Automated-change-IP-procedure-a75b5aba68e546f19efb2be4bd87d6ac

**Comment by DmytroNazarenko** [comment]
2.6.0-beta.0

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
admin: `2.6.0-beta.0`
skale-manager: `1.10.0-beta.0`

Once `ChangeIP` [transaction](https://eth-holesky.blockscout.com/tx/0x726c11993a7dfeabe02818fbd8154d09863f21768eff67b4c20c392477d74858) passed on Nodes contract, 
- `"reload_ts"` (timestamp when skaled and ima must be recreated by admin) was set to `external.json` file 
```
 "reload_ts": 1707334368
```
- and `ReloadIpSkaledMonitor` started working. 
```
[2024-02-07 19:10:39,292 INFO][82621][glamorous-sargas][T_0] - core.schains.monitor.skaled_monitor:51 - Skaled monitor type starting ReloadIpSkaledMonitor
```
- Skaled exited at `"reload_ts"` and admin recreated skaled and ima.
- After that `"reload_ts"` was set to Null
```
"reload_ts": null
```
- And admin started running `UpdateConfigSkaledMonitor` and skaled config was updated with new IP info.
```
[2024-02-07 19:33:19,562 INFO][82621][glamorous-sargas][T_0] - core.schains.monitor.skaled_monitor:51 - Skaled monitor type starting UpdateConfigSkaledMonitor
```
