### ISSUE TITLE
Share SGX certificates folder and key name with IMA container 

### ISSUE THREAD

**Issue by badrogger** [skalenetwork/skale-admin#852]
IMA container will interact with SGX directly (without middleman skaled) https://github.com/skalenetwork/skale-consensus/issues/686. So SGX account configuration will be needed. Admin need to provide it during IMA container creation.

**Comment by badrogger** [comment]
It's already done. IMA agent can use the following command line parameters. 
```
--sgx-url-s-chain=$SGX_URL \
--sgx-ecdsa-key-s-chain=$ECDSA_KEY_NAME \
--sgx-ssl-key-s-chain=$SGX_SSL_KEY_PATH \
--sgx-ssl-cert-s-chain=$SGX_SSL_CERT_PATH \
```
@sergiy-skalelabs please check this out

**Comment by badrogger** [comment]
To support full signing procedure migration from skaled to IMA agent web server should be launched to communicate with other node SGX endpoints. So another interface i.e. exposed port is needed. That requires modification in firewall rules, schain config and container runner code in skale-admin. Suggest to add the following in the scope of this tasks @sergiy-skalelabs @dmitry-tk @gannakulikova

**Comment by sergiy-skalelabs** [comment]
Yes. We can call **Skale Manager** and find out IP addresses and ports of any node of any **S-Chain**. This is how **IMA Agents** find all `skaled`s of own or other **S-Chains**. We need each **IMA Agent** to become JSON RPC server with one port open outside and **Skale Manager** provide ability to find out IP address and port of each **IMA Agent**.

**Comment by badrogger** [comment]
@sergiy-skalelabs  created separate ticket for it https://github.com/skalenetwork/IMA/issues/1289.

**Comment by DmytroNazarenko** [comment]
admin: [2.5.0-beta.0](https://github.com/skalenetwork/skale-admin/releases/tag/2.5.0-beta.0)
IMA: [2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)

**Comment by EvgeniyZZ** [comment]
Resolved
