### ISSUE TITLE
Remove --public-key argument from command line for creating skaled-container 

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skale-admin#861]
Skaled read public-key argument from schain config: all BLS public keys are located in the rotation history. 
Skale admin set  --public-key in command line for creating skaled-container. This argument is deprecated and needs to be removed 

```
root@ip-172-31-63-163:~# docker logs skale_schain_clean-wasat 
Invalid argument: --public-key
root@ip-172-31-63-163:~# docker inspect skale_schain_clean-wasat | grep public-key
            "--public-key",
                "--public-key",
```

**Comment by dmytrotkk** [comment]
How to verify:

1. Update SKALE Node to the latest version
2. Run repair procedure for one of the chains 
3. Wait until skaled container will be restarted by admin with download snapshot options 
4. Check container params: `docker inspect [SCHAIN_CONTAINER_NAME] | grep public-key` - should output nothing

CC @yatsunastya

**Comment by yatsunastya** [comment]
```docker inspect [SCHAIN_CONTAINER_NAME] | grep public-key``` -  output nothing
checked with  admin: 2.3.11-beta.2 | skaled: 3.14.15-stable.2 (but this version skaled crashes)

**Comment by yatsunastya** [comment]
checked with admin: `2.4.0-beta.1` and skaled: `3.16.0-beta.6`

```
root@ip-172-31-59-18:~# docker inspect skale_schain_quiet-alchiba | grep public-key
root@ip-172-31-59-18:~#
```
