### ISSUE TITLE
Set patch timestamps for sChain

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-admin#871]
Need to set patch timestamps for sChain configs:

1. revertableFSPatchTimestamp - patch for enabling revertable filestorage precompileds: 
2. contractStoragePatchTimestamp - timestamp for enabling contractStoragePatch

Config example:
```
....
   "sChain": {
            ...
            "revertableFSPatchTimestamp": 1000000,
            "contractStoragePatchTimestamp": 1000000,
            ...
```

Enable `revertableFSPatchTimestamp` for https://github.com/skalenetwork/internal-support/issues/35
Enable `contractStoragePatchTimestamp` for https://github.com/skalenetwork/internal-support/issues/399

**Comment by badrogger** [comment]
What should be the source of those timestamps? Is it going to be simply hardcoded, set on skale-manager or put in skale-node?

**Comment by badrogger** [comment]
To add corresponding configuration in skale-node `schain_base_config.json`

**Comment by DmytroNazarenko** [comment]
Skaled version from: [3.15.13-develop.1](https://github.com/skalenetwork/skaled/releases/tag/3.15.13-develop.1)

**Comment by DmytroNazarenko** [comment]
Enable `revertableFSPatchTimestamp` for https://github.com/skalenetwork/internal-support/issues/35

**Comment by oleksandrSydorenkoJ** [comment]
Verified on regression network 
schain: wan-tasty-kitalpha
Versions:
 skalenetwork/schain:3.16.0-beta.6
skalenetwork/admin:2.4.0-beta.1

skale-node: https://github.com/skalenetwork/skale-node/blob/b3d10e77bb216f2bab1682ee9961634cf495a2a2/static_params.yaml#L115
Schain config: 
```
 "contractStorageZeroValuePatchTimestamp": 1674554400,
            "revertableFSPatchTimestamp": 1674565200,
            "contractStoragePatchTimestamp": 1674576000,
            "verifyDaSigsPatchTimestamp": 1674586800,

```
