### ISSUE TITLE
Add "snapshotDownloadTimeout" flag to schain config + remove legacy code

### ISSUE THREAD

**Issue by oleksandrSydorenkoJ** [skalenetwork/skale-admin#891]
Related to https://github.com/skalenetwork/skaled/issues/1191

Need to add the "snapshotDownloadTimeout" flag to the schain config as an option for skaled. 

Example:
static_schain_params.json:
```
 "schain": {
        "snapshot_interval_sec": 86400,
        "empty_block_interval_ms": 10000,
        "free_contract_deployment": true,
        "snapshot_download_timeout": 18000
```

In skaled config: `snapshotDownloadTimeout`

**Comment by gannakulikova** [comment]
Assigned to 2.1 release

**Comment by DmytroNazarenko** [comment]
Feature added on skaled side from version [3.15.10-develop.0](https://github.com/skalenetwork/skaled/releases/tag/3.15.10-develop.0)
Also add `snapshotDownloadInactiveTimeout` to the same config section

**Comment by dmytrotkk** [comment]
+ also going to move these params from the `static_schain_params.json` file to [environment_params.yaml](https://github.com/skalenetwork/skale-node/blob/develop/environment_params.yaml), so they can be separated by envs. 

params that will be moved in the new version:

```
"snapshot_interval_sec": 86400,
"empty_block_interval_ms": 10000,
"free_contract_deployment": true
```

**Comment by DmytroNazarenko** [comment]
* also medium chain static params should be updated. New values:

```
transactionQueueSize: 1000
maxOpenLeveldbFiles: 1000
```

**Comment by DmytroNazarenko** [comment]
skale-node: beta
skale-admin: [2.4.0-beta.1](https://github.com/skalenetwork/skale-admin/releases/tag/2.4.0-beta.1)

**Comment by OleksanderSalamatov** [comment]
Verified on skaled: 3.16.0-beta.16, admin 2.4.0
Parameters added from skale-node and admin side
Approved that changing parameters in skale-node change corresponding variables in skaled 
Cases on testrail: C935, C936

Functionality from skaled side with default and custom timeouts was tested in:
https://github.com/skalenetwork/skaled/issues/1191
https://github.com/skalenetwork/skaled/issues/1033
