### ISSUE TITLE
Add context predeployed contract

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-admin#893]
Take context predeployed contract not from skale-node, but in the same way as other predeployeds from:
https://pypi.org/project/context-predeployed/

**Comment by gannakulikova** [comment]
Assigned to 2.1 release after confirming with @DmytroNazarenko

**Comment by DmytroNazarenko** [comment]
[2.4.0-beta.1](https://github.com/skalenetwork/skale-admin/releases/tag/2.4.0-beta.1)

**Comment by OleksanderSalamatov** [comment]
Approved on admin: 2.4.0-beta.1
Context-contract remains fully functional
Testrun in testrail: R178 in skaled section

**Comment by OleksanderSalamatov** [comment]
In admin: 2.4.0-beta.2 context-predeployed is included in admin/requirements.txt, not in skale-node
`context-predeployed==1.0.0b0`
