### ISSUE TITLE
Sync node should support different mainnet versions 

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-admin#894]
Sync/archive node should support both v2 and v2.1 chains on mainnet. So should have different predeployed contract versions in config for different versions. The version of chain should be passed via sync-node-cli.

**Comment by gannakulikova** [comment]
Assigned to 2.1 release per discussion with @kladkogex @DmytroNazarenko

**Comment by dmytrotkk** [comment]
I don't think it's a good idea to do it like that. 
Has to be discussed first.

CC @gannakulikova

**Comment by DmytroNazarenko** [comment]
Should be solved by https://github.com/skalenetwork/skaled/issues/1450
