### ISSUE TITLE
Upgrade to use python 3.11

### ISSUE THREAD

**Issue by DmytroNazarenko** [skalenetwork/skale-admin#903]
We're currently using Python 3.7 for most of our repos (release date: 2018-06-27 with the end of support 2023-06-27).
Lots of performance improvements were introduces since then, for example:

```
CPython 3.11 is on average 25% faster than CPython 3.10 when measured with the pyperformance benchmark suite, and compiled with GCC on Ubuntu Linux. Depending on your workload, the speedup could be up to 10-60% faster.
```

Upgrading Python to 3.11 shouldn't break anything for our customers, since all code will be used in docker containers.

**Comment by badrogger** [comment]
Completed in 2.3.x
