### ISSUE TITLE
Skaled should be started by skaleadmin first

### ISSUE THREAD

**Issue by kladkogex** [skalenetwork/skale-admin#942]
**Describe the bug**

Currently there are cases where failed DKG can prevent skaled from start.

**Expected behavior**

Skaled needs to run nomatter what happens to to DKG

One way to to do it is to handle skaled first when skaledadmin starts.

Cleaner way is to have a separate skaled restart agent (may be systemd or similar)
and have skale-admin talk to this agent

**Comment by DmytroNazarenko** [comment]
Scope 2.2 for this ticket: 
- Extract config generation into separate process that will run DKG + config generation
- Skaled process will change firewall rules, validate config, restart skaled, skaled healthchecks

**Comment by DmytroNazarenko** [comment]
skale-manager: 1.9.4-beta.0
skale-admin: 2.5.0-beta.1

**Comment by yatsunastya** [comment]
Blocked by https://github.com/skalenetwork/internal-support/issues/851

**Comment by yatsunastya** [comment]
Checked ✅
admin: 2.5.1-develop.2

- `upstrem config` is successfully created after each node rotation (no matter what happens with DKG)
- After removing skaled container during DKG, admin recreated it and skaled successfully started mining blocks
