### ISSUE TITLE
`ComplaintBadData` is sent during node rotation

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/skale-admin#974]
Admin: `2.5.1-develop.4`
Schain: `free-basic-rosy-SKALE`

**To Reproduce**
1. Start node rotation procedure
2. First round - Node 63 doesn't send broadcast (turned off admin), [`Complaint`](https://goerli.etherscan.io/tx/0xdf1942659822e23eef067e0cb807182a4c99f5c11862953e67bcde6f957ba24c)
3. Second round - all nodes send `broadcast`, one [`alright`](https://goerli.etherscan.io/tx/0xd7d5a0e17c6be0b71cc1ffebd4689dd69848cde4c558a8785c75a5676cf12101) is sent, and right after that [`Complaint Bad Data`](https://goerli.etherscan.io/tx/0xf0b75664788599c07311f9fe7bda99c55e3ba10f91e554e6f0f3940f8c89bb27) is sent
4. Node 31 doesn't send `PreResponse` and `Response` and in 30 min [`Complaint`](https://goerli.etherscan.io/tx/0x2c0dfa6a84a7863a678ee2a279ac48ff0b76e453519364263eead96325b3f1ed) is sent on Node 31
5. Third round - successful
6. DKG is finished after `finish_ts` so admin doesn't send `setExitTime`

[16_node_admin.txt](https://github.com/skalenetwork/skale-admin/files/12552771/16_node_admin.txt)
[31_node_admin.txt](https://github.com/skalenetwork/skale-admin/files/12552799/31_node_admin.txt)
[9_node_admin.txt](https://github.com/skalenetwork/skale-admin/files/12552823/9_node_admin.txt)

**Comment by olehnikolaiev** [comment]
related to https://github.com/skalenetwork/skale-manager/issues/1035. suggest to close or retest after the corresponding task will be completed

**Comment by DmytroNazarenko** [comment]
skale-admin: 2.6.0-beta.0

**Comment by yatsunastya** [comment]
Checked :white_check_mark: 
admin: 2.6.0-beta.0

No `ComplaintBadData` transactions were sent, only regular `Complaint`s. 
DKG was finished before `Exit_time`, so skaled exited at TS which was set in `rotation.json` file.
