### ISSUE TITLE
Admin restarts skaled container instead of recreating after node rotation

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/skale-admin#976]
It's not reproducible every node rotation

**Describe the bug**
Each n seconds admin does set of checks and on the base of its results admin chooses monitor type. 
During node rotation, after finish TS admin recreates skaled containers on all staying nodes. 

In this case, admin got the results of its checks and chose Regular Monitor. And when skaled exited at finish TS, admin just restarted it, as it's expected during Regular Monitor. 
As a result skaled container and schain config weren't recreated.
```
[2023-09-13 16:49:32,103 INFO][18679][free-basic-rosy-SKALE][T_0] - core.schains.monitor.containers:94 - sChain free-basic-rosy-SKALE: restarting container
[2023-09-13 16:49:32,104 INFO][18679][free-basic-rosy-SKALE][T_0] - core.schains.runner:167 - 
====================================================================================================
Restarting container...
Container name: skale_schain_free-basic-rosy-SKALE
====================================================================================================
```

The problem is that skaled exited just after recording checks results, so the results for admin and real state are different. 

**Version:**
Admin: 2.5.1-develop.4

**Logs:**
[admin_restarts.txt](https://github.com/skalenetwork/skale-admin/files/12601299/admin_restarts.txt)

**Comment by DmytroNazarenko** [comment]
The problem is that skaled finished with exit code 1 during node rotation, in previous release it was finishing with code 0

**Comment by DmytroNazarenko** [comment]
skaled: 3.17.0-beta.9

**Comment by yatsunastya** [comment]
checked :white_check_mark: 
skaled: 3.17.1

Now, after rotation, skaled on leaving node exits with 0 exit code, and the problem wasn't reproduced.
