### ISSUE TITLE
`exit_zero` failed checks are sent too often 

### ISSUE THREAD

**Issue by yatsunastya** [skalenetwork/skale-admin#982]
**Describe the bug**
Admin regularly checks if skaled exited with 0 exit code and sends notification to telegram each time. 

<img width="556" alt="Знімок екрана 2023-09-22 о 15 53 56" src="https://github.com/skalenetwork/skale-admin/assets/105824131/27463a3b-1b11-414c-9eae-9fd92a2f046d">

**Comment by DmytroNazarenko** [comment]
[2.5.1-develop.6](https://github.com/skalenetwork/skale-admin/releases/tag/2.5.1-develop.6)

**Comment by yatsunastya** [comment]
checked :white_check_mark: 
admin: 2.5.1-develop.7
