### ISSUE TITLE
Node rotation: Admin was not restart IMA Agent after finish ts 

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/skale-admin#989]
**Description**
Admin was not restart IMA Agent after finish ts 
Network: Any 
Schain: at least one on the network
Skale admin: 2.5.1-develop.7

**Steps**
1. Execute node exit on one node
2. Wait finish ts
3. Check BLS keys used on staying nodes

**Expected behavior**
Ima container restarted and use new keys

**Actual**
Ima agent didn't restarted and use previous keys

**Comment by DmytroNazarenko** [comment]
2.5.0

**Comment by EvgeniyZZ** [comment]
Verified: IMA Agent container restarted/recreated after node rotation finish_ts
Version: 2.5.3 


[imaBlsRotation.txt](https://github.com/skalenetwork/skale-admin/files/13474665/imaBlsRotation.txt)
